---

- name: "Check value of 'metallb[version]' variable"
  ansible.builtin.fail:
    msg: "You should set value of 'metallb[version]' variable"
  when: metallb["version"] == None

- name: "Check value of 'metallb[pool_name]' variable"
  ansible.builtin.fail:
    msg: "You should set value of 'metallb[pool_name]' variable"
  when: metallb["pool_name"] == None

- name: "Check value of 'user_name' variable"
  ansible.builtin.fail:
    msg: "You should set value of 'user_name' variable"
  when: user_name == None