---
- name: Actions for controls nodes
  block:
    - name: Disabled swap
      ansible.builtin.command: swapoff -a
      become: true

    - name: Change hostname
      ansible.builtin.command: "hostnamectl set-hostname {{ inventory_hostname }}"

    - name: Initialize the cluster
      ansible.builtin.shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: Create .kube directory
      become: yes
      become_user: "{{ user_name }}"
      ansible.builtin.file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Copy admin.conf to user's kube config
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ user_name }}/.kube/config"
        remote_src: yes
        owner: "{{user_name}}"

    - name: Install Pod network
      become: yes
      become_user: "{{ user_name }}"
      ansible.builtin.shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
  when: inventory_hostname in groups['control_nodes']
