---
- name: Install utils
  ansible.builtin.apt:
    pkg:
      - curl
      - gnupg2 
      - software-properties-common 
      - apt-transport-https 
      - ca-certificates
    state: present
    update_cache: true

- ansible.builtin.include_tasks: containerd_installation.yaml

- name: Add Kubernetes apt-key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes' APT repository
  ansible.builtin.apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: "kubernetes"

- name: Install kubelet kubeadm kubectl
  become: yes
  ansible.builtin.apt:
    pkg:
      - kubelet
      - kubeadm
      - kubectl 
    state: present
    update_cache: true

- name: Hold kubelet kubeadm kubectl
  become: yes
  ansible.builtin.shell: apt-mark hold kubelet kubeadm kubectl

- name: Enable kubectl autocompletion
  become: yes
  become_user: "{{ user_name }}"
  args:
    chdir: $HOME
  ansible.builtin.shell: echo 'source <(kubectl completion bash)' >>~/.bashrc
  when: inventory_hostname in groups['control_nodes']

- name: Stop apparmor
  ansible.builtin.service:
    name: apparmor 
    state: stopped

- name: Disabled apparmor
  ansible.builtin.service:
    name: apparmor
    enabled: no

- name: restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted