---
- name: Create Docker config directory
  ansible.builtin.file:
    path: "/etc/docker"
    state: directory

- name: Changing Docker to systemd driver
  ansible.builtin.copy:
    dest: "/etc/docker/deamon.json"
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"]
      }

- name: Install Docker
  ansible.builtin.apt:
    name: docker.io
    state: present
    update_cache: true

- name: Install APT Transport HTTPS
  ansible.builtin.apt:
    name: apt-transport-https
    state: present

- name: Install gnupg
  ansible.builtin.apt:
    name: gnupg
    state: present
    update_cache: true

- name: Add Kubernetes apt-key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes' APT repository
  ansible.builtin.apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: "kubernetes"

- name: Install kubelet
  ansible.builtin.apt:
    name: 'kubelet={{ kubernetes["utils_version"] }}'
    state: present
    update_cache: true

- name: Install kubeadm
  ansible.builtin.apt:
    name: 'kubeadm={{ kubernetes["utils_version"] }}'
    state: present

- name: Install kubectl
  block:
    - name: Install kubectl
      ansible.builtin.apt:
        name: 'kubectl={{ kubernetes["utils_version"] }}'
        state: present
        force: yes

    - name: Enable kubectl autocompletion
      become: yes
      become_user: "{{ user_name }}"
      args:
        chdir: $HOME
      ansible.builtin.shell: echo 'source <(kubectl completion bash)' >>~/.bashrc

  when: inventory_hostname in groups['control_nodes']
