---
- name: Actions for controle nodes
  block:
    - name: Prepare cluster for MetalLB
      args:
        chdir: $HOME
      ansible.builtin.shell: |
        kubectl get configmap kube-proxy -n kube-system -o yaml |
        sed -e "s/strictARP: false/strictARP: true/" |
        sed -e "s/mode: \"\"/mode: \"ipvs\"/" |
        kubectl apply -f - -n kube-system

    - name: Create values.yaml file for MetalLB
      ansible.builtin.template:
        src: "values.j2"
        dest: "$HOME/values.yaml"

    - name: Add MetalLB repo to helm
      args:
        chdir: $HOME
      ansible.builtin.shell: helm repo add metallb https://metallb.github.io/metallb

    - name: Install metallb MetalLB
      args:
        chdir: $HOME
      ansible.builtin.shell: helm install metallb metallb/metallb -f values.yaml
  when: inventory_hostname in groups['control_nodes']
  become: yes
  become_user: "{{ user_name }}"
