---
- name: Actions for controle nodes
  block:
    - name: Prepare cluster for MetalLB
      args:
        chdir: $HOME
      ansible.builtin.shell: |
        kubectl get configmap kube-proxy -n kube-system -o yaml |
        sed -e "s/strictARP: false/strictARP: true/" |
        sed -e "s/mode: \"\"/mode: \"ipvs\"/" |
        kubectl apply -f - -n kube-system

    - name: Create metallb-pool.yaml file for MetalLB
      ansible.builtin.template:
        src: "metallb-pool.j2"
        dest: "$HOME/metallb-pool.yaml"

    - name: Install metallb-native
      args:
        chdir: $HOME
      ansible.builtin.shell: 'kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v{{ kubernetes["metallb_version"] }}/config/manifests/metallb-native.yaml'
    
    - name: Apply metall-pull.yaml file
      args:
        chdir: $HOME
      ansible.builtin.shell: kubectl apply -f metallb-pool.yaml 
      retries: 3
      delay: 10
      register: task_result
      until: task_result.rc == 0 

  when: inventory_hostname in groups['control_nodes']
  become: yes
  become_user: "{{ user_name }}"
