---
- name: Actions for workers nodes
  block:
    - name: Get join command
      ansible.builtin.shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command
      ansible.builtin.set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"
  when: inventory_hostname in groups['control_nodes']

- name: Actions for workers nodes
  block:
    - name: Disabled swap
      ansible.builtin.command: swapoff -a
      become: true

    - name: Change hostname
      ansible.builtin.command: "hostnamectl set-hostname {{ inventory_hostname }}"

    - name: Join cluster
      ansible.builtin.shell: "{{ hostvars['control_node_1'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
  when: inventory_hostname in groups['worker_nodes']
